name: Build OpenRV with FFmpeg

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential cmake ninja-build git \
          yasm nasm pkg-config libtool autoconf automake \
          libgl1-mesa-dev libx11-dev libxext-dev libxrandr-dev \
          libxi-dev libxinerama-dev libxcursor-dev libxss-dev \
          libasound2-dev libpulse-dev python3 python3-pip \
          libopenexr-dev libopenimageio-dev \
          libx264-dev libx265-dev libvpx-dev libfdk-aac-dev \
          libmp3lame-dev libopus-dev libxvidcore-dev \
          zlib1g-dev libbz2-dev libssl-dev libffi-dev

    - name: Build FFmpeg
      run: |
        git clone https://github.com/FFmpeg/FFmpeg.git
        cd FFmpeg
        ./configure --prefix=$HOME/ffmpeg_install \
          --enable-gpl --enable-nonfree \
          --enable-libx2
